name: 'AWS Okta Authenticator'
description: 'Authenticate using aws-okta-processor and return AWS Credentials for temporarily assumed role'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  aws-okta-user:
    description: 'Jomax user to use to assume temporary role'
    required: true
  aws-okta-pass: # Use GitHub Actions Secrets to pass this in from the upstream job. 
    description: 'Jomax password for user'
    required: true
  aws-okta-organization:
    description: 'Okta organization'
    required: false
    default: 'godaddy.okta.com' # Defaults to standard GoDaddy AWS Okta organization
  aws-okta-application:
    description: 'Okta application'
    required: false
    default: 'https://godaddy.okta.com/home/amazon_aws/0oakmpp1rkb2ZuZsQ0x7/272' # Default to Non-PCI
  aws-okta-role: 
    description: 'ARN of AWS Role to assume'
    required: true
  aws-region:
    description: 'Default AWS Region'
    required: false
    default: 'us-west-2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-okta-user }}
    - ${{ inputs.aws-okta-pass }}
    - ${{ inputs.aws-okta-organization }}
    - ${{ inputs.aws-okta-application }}
    - ${{ inputs.aws-okta-role }}
    - ${{ inputs.aws-region }} 
