name: 'Tartufo secret scanner'
description: 'Scans your repository for secrets'
inputs:
  github_token:
    description: 'A github access token with access to clone repository history'
    required: true
  current_event_only:
    description: 'sets the --branch and --since-commit options based on the values in the current github event'
    required: false
    default: "false"
  options:
    description: 'Override default options for scanning'
    required: false
runs:
  using: "composite"
  steps:
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@a17646e2633d1f79886a1530ccce16c95a3bb8dc
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Add a github secret with your Deploy User AccessKeyId from AWS Secrets Manager
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Add a github secret with your Deploy User SecretAccessKey from AWS Secrets Manager
      role-to-assume: arn:aws:iam::664122783931:role/GD-AWS-USA-CTO-JenkinsonAWS-Dev-Private-Deploy # Your deploy role ARN 
      role-duration-seconds: 7200 # default max is 7200
      aws-region: us-west-2 # set region you want to target

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@41032bd0f8164c350fb597a5e1ec886624de7465

  using: 'docker'
  image: 'Dockerfile'
