name: 'Tartufo secret scanner'
description: 'Scans your repository for secrets'
inputs:
  github_token:
    description: 'A github access token with access to clone repository history'
    required: true
  current_event_only:
    description: 'sets the --branch and --since-commit options based on the values in the current github event'
    required: false
    default: "false"
  options:
    description: 'Override default options for scanning'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
