repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: detect-private-key
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: fix-byte-order-marker
- repo: https://github.com/godaddy/tartufo
  rev: stable
  hooks:
  - id: tartufo
