# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Connect AWS ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: sjacoby-godaddy/rainyday
        path: my-tools

    - name: Tartufo secret scanning using the Tartufo GitHub Action
      uses: ./my-tools
      with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN }}
          options: "--regex --json"

